package androidx.lifecycle.runtime

// Build-mechanism shim, NOT application code (not part of embedded_kotlin/'s real source tree).
// androidx.lifecycle's ViewTreeLifecycleOwner.set()/get() key a View.setTag(int, Object) slot by
// this library's own R.id.view_tree_lifecycle_owner - normally generated by AAPT2 at final-app-link
// time (the AAR's own R.txt ships only a `0x0` placeholder; real apps get a real value assigned by
// their own build). This hand-rolled manual kotlinc+d8 pipeline has no AAPT2/resource-linking step
// at all, so nothing generates this class automatically - a real gap the CMake automation for this
// pipeline will need to solve properly (see embedded_kotlin/README.md). The exact numeric value
// only needs to be self-consistent within this module (same class used for both the setter and
// getter call sites, compiled from the same androidx.lifecycle:lifecycle-runtime-android jar) and
// not collide with a real Android framework view tag - it does not need to match what a real AAPT2
// build would assign, since no other resource table exists in this process to collide against.
class R {
    object id {
        const val view_tree_lifecycle_owner: Int = 0x7f0d0001
    }
}
