# Build-time driver invoked via `cmake -P` from konative_embed_binary_blob()'s
# add_custom_command. Deliberately NOT a configure_file() .S.in template - see
# KonativeEmbedBlob.cmake / research/incbin_embedding_research.md section 2
# for why this must run at build time, not configure time.
foreach(_required KONATIVE_BLOB_PATH KONATIVE_BLOB_SYMBOL KONATIVE_OUT_FILE)
  if(NOT DEFINED ${_required})
    message(FATAL_ERROR "KonativeGenerateIncbinAsm.cmake: ${_required} must be passed via -D")
  endif()
endforeach()

# Optional: emit a <prefix>_expected_sha256[32] alongside the blob, computed fresh from the same
# real bytes every time this script runs (build time, same trigger as the .incbin regeneration
# itself - see KonativeEmbedBlob.cmake's VERIFY_SHA256 doc comment). CMake's own builtin file(SHA256
# ...) needs no extra dependency for this half; only the RUNTIME re-hash (checked_blob.hpp) needs
# PicoSHA2.
set(_sha256_asm "")
if(KONATIVE_VERIFY_SHA256)
  file(SHA256 "${KONATIVE_BLOB_PATH}" _hash_hex)
  set(_byte_lines "")
  foreach(_i RANGE 0 62 2)
    string(SUBSTRING "${_hash_hex}" ${_i} 2 _byte_hex)
    string(APPEND _byte_lines "    .byte 0x${_byte_hex}\n")
  endforeach()
  set(_sha256_asm "\
    .balign 8
    .global ${KONATIVE_BLOB_SYMBOL}_expected_sha256
${KONATIVE_BLOB_SYMBOL}_expected_sha256:
${_byte_lines}\
")
endif()

# No `.type sym, @object`/`%object` anywhere below - GNU as/LLVM's integrated
# assembler use `@` on most targets but ARM/AArch64 conventionally want `%`
# instead (`@` is that target's comment leader) - three independently
# converging sources in research/incbin_embedding_research.md section 1.
# Omitting `.type` entirely sidesteps the question: it's pure ELF-symbol-table
# metadata, load-bearing for nothing here (only ever take these symbols'
# addresses). `.balign` (not the ARM-power-of-two-ambiguous `.align`) and an
# explicit `"a"` section flag (custom section names don't get free defaults
# the way exactly `.rodata` does) for the same "verified, not guessed" reason.
file(WRITE "${KONATIVE_OUT_FILE}" "\
/* Auto-generated by KonativeGenerateIncbinAsm.cmake - do not hand-edit. */
    .section .rodata.konative.${KONATIVE_BLOB_SYMBOL},\"a\"
    .balign 16
    .global ${KONATIVE_BLOB_SYMBOL}_start
${KONATIVE_BLOB_SYMBOL}_start:
    .incbin \"${KONATIVE_BLOB_PATH}\"
    .global ${KONATIVE_BLOB_SYMBOL}_end
${KONATIVE_BLOB_SYMBOL}_end:

    .balign 8
    .global ${KONATIVE_BLOB_SYMBOL}_size
${KONATIVE_BLOB_SYMBOL}_size:
    .quad ${KONATIVE_BLOB_SYMBOL}_end - ${KONATIVE_BLOB_SYMBOL}_start

${_sha256_asm}\
    /* Hand-written .S objects skip the compiler's automatic PT_GNU_STACK
       marking - omitting this can make some lld configurations warn/error
       \"missing .note.GNU-stack section implies executable stack\". */
    .section .note.GNU-stack,\"\"
")
